baseURL = "https://sublog.zinntikumugai.com/"
languageCode = "ja"
title = "さぶろぐ!"
theme = "cleanwhite"

disqusShortname = "zin3sublog"
googleAnalytics = "UA-82826188-14"

[params]
  [params.social]
  rss       = true
  twitter   = "https://twitter.com/uesitananame55"
  github    = "https://github.com/zinntikumugai/"