baseURL = "https://sublog.zinntikumugai.com/"
languageCode = "ja"
title = "さぶろぐ!"

disqusShortname = "zin3sublog"
googleAnalytics = "UA-82826188-14"

# theme config
[params]
style = "auto"
fullRss = true

[params.assets]
css = ["css/font.css"]   # fonts

[params.comments]
enable = true

[params.nav]
showCategories = true
showTags = true

[[params.nav.custom]]
title = "Currency.ovh"
url = "https://Currency.ovh"

[[params.nav.custom]]
title = "GitHub"
url = "https://github.com/zinntikumugai/"

[[params.nav.custom]]
title = "Twitter"
url = "https://twitter.com/uesitananame55"

[module]
    [[module.imports]]
    path="github.com/cntrump/hugo-notepadium"