baseURL = "https://sublog.zinntikumugai.com/"
languageCode = "ja"
title = "さぶろぐ!"

disqusShortname = "zin3sublog"
googleAnalytics = "UA-82826188-14"

[frontmatter]
    date = ["date", "publishDate", "lastmod"]
    lastmod = [":git", "lastmod", "date", "publishDate"]
    publishDate = ["publishDate", "date"]
    expiryDate = ["expiryDate"]
[params]

    bookmarks = true
    [[params.bookmark_link]]
    title = "Currency.ovh"
    href = "https://Currency.ovh"

    [params.social]
    rss       = true
    twitter   = "https://twitter.com/uesitananame55"
    github    = "https://github.com/zinntikumugai/"

[module]
    [[module.imports]]
    path="github.com/zhaohuabing/hugo-theme-cleanwhite"